/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Check if the native addon loaded successfully */
export declare function healthCheck(): string
/** Hardware encoder availability */
export interface EncoderSupport {
  /** NVIDIA NVENC available */
  nvenc: boolean
  /** AMD AMF available (future) */
  amf: boolean
  /** Intel QuickSync available (future) */
  quicksync: boolean
  /** Software x264 fallback */
  software: boolean
}
/** Check which hardware encoders are available on this system */
export declare function getEncoderSupport(): EncoderSupport
/** Display information for capture */
export interface DisplayInfo {
  /** Display index (0-based) */
  index: number
  /** Display name */
  name: string
  /** Width in pixels */
  width: number
  /** Height in pixels */
  height: number
  /** Primary display flag */
  isPrimary: boolean
}
/** Get list of available displays for capture */
export declare function getDisplays(): Array<DisplayInfo>
/** Capture settings */
export interface CaptureSettings {
  /** Display index to capture */
  displayIndex: number
  /** Target frames per second */
  fps: number
  /** Target bitrate in bits per second */
  bitrate: number
  /** Use hardware encoder (NVENC if available) */
  useHardwareEncoder: boolean
}
/** Encoded frame data */
export interface EncodedFrame {
  /** Frame number (sequential) */
  frameNumber: number
  /** Timestamp in microseconds */
  timestampUs: number
  /** Is this a keyframe (I-frame)? */
  isKeyframe: boolean
  /** Encoded H264 data (Annex B format) */
  data: Buffer
}
/**
 * Start hardware capture and encoding
 *
 * Returns a stream of encoded frames via the callback
 */
export declare function startCapture(settings: CaptureSettings, callback: (frame: EncodedFrame) => void): void
/** Stop the running capture */
export declare function stopCapture(): void
/** Check if capture is currently running */
export declare function isCaptureRunning(): boolean
