/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function healthCheck(): string
export interface EncoderSupport {
  nvenc: boolean
  amf: boolean
  quicksync: boolean
  software: boolean
}
export declare function getEncoderSupport(): EncoderSupport
export interface DisplayInfo {
  index: number
  name: string
  width: number
  height: number
  isPrimary: boolean
}
export declare function getDisplays(): Array<DisplayInfo>
export interface CaptureSettings {
  displayIndex: number
  fps: number
  bitrate: number
  useHardwareEncoder: boolean
}
export interface EncodedFrame {
  frameNumber: number
  timestampUs: number
  isKeyframe: boolean
  data: Buffer
}
export declare function startCapture(settings: CaptureSettings, callback: (frame: EncodedFrame) => void): void
export declare function stopCapture(): void
export declare function isCaptureRunning(): boolean
/** UDP Network Client for TitanLink */
export declare class NetworkClient {
  constructor()
  /** Connect to remote peer (or relay server) */
  connect(remoteIp: string, remotePort: number, sessionId: string): void
  /** Send handshake to initiate session */
  sendHandshake(): void
  /** Send video frame (fire-and-forget) */
  sendVideoFrame(frameNumber: number, codec: number, isKeyframe: boolean, frameData: Buffer): void
  /** Send controller input (reliable) */
  sendControllerInput(controllerIndex: number, buttons: number, leftStickX: number, leftStickY: number, rightStickX: number, rightStickY: number, leftTrigger: number, rightTrigger: number): void
  /** Send keep-alive packet */
  sendKeepAlive(): void
  /** Disconnect and cleanup */
  disconnect(): void
  /** Start listening for incoming packets */
  startListening(callback: (data: Buffer) => void): void
  /** Check if connected */
  isConnected(): boolean
}
